export * as Input from './input';
export * as Button from './button';
export * as Card from './card';
export * as Typhograpy from './typography';
export { default as Gap } from './Gap';
export { default as HeaderPage } from './HeaderPage';
export { default as RatingStart } from './RatingStart';
export { default as QuestionWithAction } from './QuestionWithAction';
export { default as ItemOrder } from './ItemOrder';
export { default as Dashed } from './Dashed';
export { default as MenuProfile } from './MenuProfile';
